#指定Erueka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka


#指定具体服务的负载均衡策略
SEARCH:        #编写服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


feign:
  hystrix:
    enabled: true

version: v1
#指定服务的名称
spring:
  application:
    name: CUSTOMER-${version}

  rabbitmq:
    host: 47.95.112.105
    port: 5672
    username: test
    password: test
    virtual-host: /test
