#指定Erueka服务地址
eureka:
  client:
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-seconds: 30
    lease-expiration-duration-in-seconds: 90

#指定具体服务的负载均衡策略
SEARCH:        #编写服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


feign:
  hystrix:
    enabled: true


#指定服务的名称
spring:

  rabbitmq:
    host: 47.95.112.105
    port: 5672
    username: test
    password: test
    virtual-host: /test
